name: Docker Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Download explainshell database
        run: |
          curl -L -o ./dump.gz https://github.com/idank/explainshell/releases/download/db-dump/dump.gz
          ls -lh dump.gz

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker image
        run: docker compose build

      - name: Test API response
        run: |
          docker compose up -d
          sleep 10  # Wait for services to start
          curl -s "http://localhost:5000/api/explain?cmd=ls+-lh" | jq . 

      - name: Extract Git tag, branch, and commit shortlog
        id: vars
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF}" == refs/heads/* ]]; then
            echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          fi
          short_commit=$(git rev-parse --short HEAD)
          echo "short_commit=$short_commit" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Tag and Push Docker image
        run: |
          if [ -n "$tag" ]; then
            docker tag explainshell-api gryffus/explainshell-api:$tag
          fi
          if [ -n "$short_commit" ]; then
            docker tag explainshell-api gryffus/explainshell-api:$short_commit
          fi
          if [ "$branch" == "main" ]; then
            docker tag explainshell-api gryffus/explainshell-api:latest
          fi
          docker push --all-tags gryffus/explainshell-api
